Update `windows-install-hosts.bat` reference
Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist pull request #704
Opened 2024-11-22 23:02 UTC by emmanuel-ferdman

# PR Summary
Small PR - fixes the broken  `windows-install-hosts.bat` reference in the docs.

2024-11-23 07:56 UTC, spirillen approved these changes
LGTM

2024-12-09 19:21 UTC, emmanuel-ferdman commented
@funilrys @mitchellkrogza please review this small PR when you get the chance

2024-12-09 19:30 UTC, spirillen requested changes
Come to my attention, that the README are generated from a template, so you need to make the change to this line instead

https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/blob/1debeb35a9c817c5e91649491565002b71f8dcd3/templates/README_template.md?plain=1#L225

2024-12-09 19:33 UTC, emmanuel-ferdman commented
@spirillen I did change `/templates/README_template.md` in this PR. Should I just revert the `/README.md`?

2024-12-09 19:48 UTC, spirillen commented
> @spirillen I did change `/templates/README_template.md` in this PR. Should I just revert the `/README.md`?

No no, my bad. but when I was looking at https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/pull/704/files I didn't notice you was working on the template :)

Just sit back a relax with a cup of coffee

2024-12-18 18:41 UTC, spirillen commented
/merge

2024-12-30 08:21 UTC, emmanuel-ferdman commented
@spirillen looks like it didn't merge, please check when you get the chance

2024-12-31 06:42 UTC, spirillen commented
> @spirillen looks like it didn't merge, please check when you get the chance

I can't merge this one, only @mitchellkrogza and maybe @funilrys have that magic power here, I was just Santa's little helper

2025-01-05 14:24 UTC, emmanuel-ferdman commented
@spirillen thank you!
@mitchellkrogza @funilrys could you please review this small PR? 🙌

2025-01-17 01:43 UTC, merged

2025-02-01 09:14 UTC, greeeny21 commented
can I use this in Linux?

2025-02-01 13:45 UTC, JonnyTech commented
> can I use this in Linux?

Look in the `Installer-Linux` folder..